content:
  - name: pagine
    label: Tutte le Pagine
    type: collection
    path: .        # Cerca i file nella cartella principale
    extension: html # Mostra solo i file .html
    fields:
      - name: title
        label: Titolo (opzionale)
        type: string
      - name: body
        label: Contenuto Pagina
        type: rich-text
